name: status_mate
display_name: Status Mate
description: "A new Flutter project."
publish_to: 'none' 

version: 1.1.0+6

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  path_provider: ^2.1.5
  permission_handler: ^11.3.0
  # gallery_saver: ^2.3.2
  # google_mobile_ads: ^4.0.0
  # flutter_local_notifications: ^15.1.0+1
  file_picker: ^9.2.2
  intl: ^0.19.0
  

  cupertino_icons: ^1.0.8
  video_player: ^2.10.0
  flutter_downloader: ^1.12.0
  share_plus: ^11.0.0
  webview_flutter: ^4.13.0
  shimmer: ^3.0.0
  dio: ^5.8.0+1
  external_path: ^2.2.0
  saver_gallery: ^4.0.1
  shared_preferences: ^2.5.3
  device_info_plus: ^10.1.0
  cross_file: ^0.3.4+2
  open_file: ^3.5.10
  media_scanner:
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icon/icon.png"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: "assets/icon/icon.png"
  android: true
  ios: true
  web: true
  android_12:
    image: "assets/icon/icon.png"
    color: "#ffffff"
